//! init_handler - Handles the execution of the init command.

use crate::commands::{args::InitArgs, init::InitCommand};
use anyhow::Result;

/// Executes the init command based on the provided arguments.
///
/// # Arguments
///
/// * `args` - Parsed command line arguments for the init command
///
/// # Returns
///
/// Returns `Ok(())` on success, or an error if:
/// - Arguments validation fails
/// - File operations fail
/// - User cancels the operation
///
/// # Example
///
///
/// use treeclip::commands::args::InitArgs;
/// use std::path::PathBuf;
///
/// let args = InitArgs {
///     directory: PathBuf::from("."),
///     force: false,
/// };
///
/// treeclip::commands::init_handler::handle(args)?;
///
pub fn handle(args: InitArgs) -> Result<()> {
    // Validate arguments.
    args.validate()?;

    // Canonicalize the directory path to get absolute path.
    let target_dir = args.directory.canonicalize()?;

    // Create and execute the init command.
    let init_cmd = InitCommand::new(target_dir, args.force);
    init_cmd.execute()?;

    Ok(())
}

#[cfg(test)]

mod init_handler_tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn test_handle_creates_file() -> Result<()> {
        let temp_dir = TempDir::new()?;
        let args = InitArgs {
            directory: temp_dir.path().to_path_buf(),
            force: false,
        };

        handle(args)?;

        let treeclip_ignore_path = temp_dir.path().join(".treeclipignore");
        assert!(treeclip_ignore_path.exists());

        Ok(())
    }

    #[test]
    fn test_handle_with_invalid_directory() {
        let args = InitArgs {
            directory: std::path::PathBuf::from("/nonexistent/dir"),
            force: false,
        };

        assert!(handle(args).is_err());
    }

    #[test]
    fn test_handle_force_overwrites() -> Result<()> {
        let temp_dir = TempDir::new()?;
        let treeclip_ignore_path = temp_dir.path().join(".treeclipignore");

        // Create existing file.
        fs::write(&treeclip_ignore_path, "old content")?;

        let args = InitArgs {
            directory: temp_dir.path().to_path_buf(),
            force: true,
        };

        handle(args)?;

        let content = fs::read_to_string(&treeclip_ignore_path)?;
        assert!(content.contains("Generated by treeclip init"));
        assert!(!content.contains("old content"));

        Ok(())
    }
}
